spring.application.name=Statistic
debug=false

# Elastic configurations
statistic-app.elastic.base-url=${ELASTIC_TOKEN:localhost:9201}
statistic-app.elastic.token=${ELASTIC_TOKEN:}
statistic-app.kibana.base-url=${KIBANA_URL:localhost:5601}

## Configuration of Statistic App
# All input features will be stored in indexes prefixed with this identifier.
statistic-app.storage.index-prefix=${INDEX_PREFIX:statistic-}
