spring.application.name=OvertureConverterBatch
debug=${DEBUG:false}
server.port=${SERVER_PORT:8102}

springdoc.api-docs.path=/v3/api-docs/openapi.json
springdoc.api-docs.version=openapi_3_0

# Elastic/Kibana configurations
statistic-app.elastic.base-url=${ELASTIC_BASE_URL:localhost:9201}
statistic-app.elastic.token=${ELASTIC_TOKEN:}
statistic-app.kibana.base-url=${KIBANA_URL:localhost:5601}

statistic-app.elasticsearch.connection-timeout=${ELASTIC_CONNECT_TIMEOUT:60s}
statistic-app.elasticsearch.socket-timeout=${ELASTIC_SOCKET_TIMEOUT:60s}
statistic-app.elasticsearch.connection-request-timeout=${ELASTIC_REQUEST_TIMEOUT:60s}
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL_SIZE:25}

## Configuration of Statistic App
# All input features will be stored in indexes prefixed with this identifier.
statistic-app.storage.index-prefix=${INDEX_PREFIX:statistic}
statistic-app.storage.feature-properties-index-suffix=${PROPERTIES_INDEX_SUFFIX:feature-properties}
statistic-app.storage.batch-size=${SAVE_ALL_TO_INDEX_BATCH_SIZE:1000}

# Kibana Dashboard
statistic-app.analytics.index-widgets-json= ${WIDGETS_JSON:src/main/resources/widgets.json}
statistic-app.analytics.diff-per-feature-type-result-index-prefix=${DIFF_PER_TYPE_INDEX_PREFIX:-difference-per-feature-type-result}
statistic-app.analytics.diff-per-feature-result-index-prefix=${DIFF_PER_FEATURE_INDEX_PREFIX:-difference-per-feature-result}
#Diff Report
statistic-app.analytics.diff-report.diff-report-out-folder-path=${DIFF_REPORT_OUT_FOLDER_PATH:}

# S3 client configuration
s3.access-key=${S3_ACCESS_KEY:}
s3.secret-key=${S3_SECRET_KEY:}
s3.region=${S3_REGION:eu-west-1}

#Batch / JOB
spring.batch.job.enabled=false

batch.jobs.enabledJobs=${BATCH_ENABLED_JOBS:SegmentJob}
batch.jobs.inputBasePath=${INPUT_BASE_PATH:.../data/overture/luxembourg/2026-02-18.0}
batch.jobs.dataVersion=${DATA_VERSION:v2026-02-18.0}

#batch.jobs.enabledJobs=mockOvertureJob
#batch.jobs.enabledJobs=SegmentJob
#batch.jobs.enabledJobs=BuildingJob,addressJob,DivisionJob,DivisionAreaJob,DivisionBoundaryJob,WaterJob,InfrastructureJob,LandJob,LandUseJob,ConnectorJob,PlaceJob,landCoverJob,SegmentJob,bathymetryJob

batch.jobs.parameters.BuildingJob.inputPath=${batch.jobs.inputBasePath}/theme=buildings/type=building/building.parquet
batch.jobs.parameters.BuildingJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.addressJob.inputPath=${batch.jobs.inputBasePath}/theme=addresses/type=address/address.parquet
batch.jobs.parameters.addressJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.DivisionJob.inputPath=${batch.jobs.inputBasePath}/theme=divisions/type=division/division.parquet
batch.jobs.parameters.DivisionJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.DivisionAreaJob.inputPath=${batch.jobs.inputBasePath}/theme=divisions/type=division_area/division_area.parquet
batch.jobs.parameters.DivisionAreaJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.DivisionBoundaryJob.inputPath=${batch.jobs.inputBasePath}/theme=divisions/type=division_boundary/division_boundary.parquet
batch.jobs.parameters.DivisionBoundaryJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.WaterJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=water/water.parquet
batch.jobs.parameters.WaterJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.InfrastructureJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=infrastructure/theme-base=type=infrastructure.parquet
batch.jobs.parameters.InfrastructureJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.LandJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=land/land.parquet
batch.jobs.parameters.LandJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.LandUseJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=land_use/land_use.parquet
batch.jobs.parameters.LandUseJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.ConnectorJob.inputPath=${batch.jobs.inputBasePath}/theme=transportation/type=connector/connector.parquet
batch.jobs.parameters.ConnectorJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.PlaceJob.inputPath=${batch.jobs.inputBasePath}/theme=places/type=place/place.parquet
batch.jobs.parameters.PlaceJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.landCoverJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=land_cover/land_cover.parquet
batch.jobs.parameters.landCoverJob.version=${batch.jobs.dataVersion}

batch.jobs.parameters.SegmentJob.inputPath=${batch.jobs.inputBasePath}/theme=transportation/type=segment/segment.parquet
batch.jobs.parameters.SegmentJob.version=${batch.jobs.dataVersion}


batch.jobs.parameters.bathymetryJob.inputPath=${batch.jobs.inputBasePath}/theme=base/type=bathymetry/bathymetry.parquet
batch.jobs.parameters.bathymetryJob.version=${batch.jobs.dataVersion}


#,,,,,,,,,,,,

# S3
# Path to the input data. Can be a single .parquet file or a folder4
#batch.jobs.parameters.mockOvertureJob.inputPath=s3://overturemaps-us-west-2/release/2025-07-23.0/theme=places/type=place/
#batch.jobs.parameters.mockOvertureJob.inputPath=s3://overturemaps-us-west-2/release/2025-07-23.0/theme=divisions/type=division/part-00000-005e8336-7417-4bbc-8cc3-df2ec08942bc-c000.zstd.parquet

# Local
# Path to the input data. Can be a single .parquet file or a folder
#batch.jobs.parameters.mockOvertureJob.inputPath=file:///C:/parquet-data/
#batch.jobs.parameters.mockOvertureJob.inputPath=file:///C:/parquet-data/kyiv_poi_placec.parquet

#Batch
batch.jobs.chunk-size=${BATCH_CHUNK_SIZE:1000}
batch.jobs.grid-size=${BATCH_GRID_SIZE:10}
batch.jobs.partition-size.rows=${BATCH_PARTITION_SIZE_ROWS:100000}
