spring.application.name=OvertureFrameworkExtensionApp
debug=false
server.port=${SERVER_PORT:8101}

springdoc.api-docs.path=/v3/api-docs/openapi.json
springdoc.api-docs.version=openapi_3_0

# Elastic/Kibana configurations
statistic-app.elastic.base-url=${ELASTIC_BASE_URL:localhost:9201}
statistic-app.elastic.token=${ELASTIC_TOKEN:}
statistic-app.elastic.connection-timeout=60s
statistic-app.elastic.socket-timeout=60s
statistic-app.kibana.base-url=${KIBANA_URL:localhost:5601}

## Configuration of Statistic App
# All input features will be stored in indexes prefixed with this identifier.
statistic-app.storage.index-prefix=${INDEX_PREFIX:statistic}
statistic-app.storage.feature-properties-index-suffix=${PROPERTIES_INDEX_SUFFIX:feature-properties}
statistic-app.storage.batch-size=${SAVE_ALL_TO_INDEX_BATCH_SIZE:100}


# Kibana Dashboard
statistic-app.analytics.index-widgets-json= ${WIDGETS_JSON:src/main/resources/widgets.json}
statistic-app.analytics.diff-per-feature-type-result-index-prefix=${DIFF_PER_TYPE_INDEX_PREFIX:-difference-per-feature-type-result}
statistic-app.analytics.diff-per-feature-result-index-prefix=${DIFF_PER_FEATURE_INDEX_PREFIX:-difference-per-feature-result}
spring.batch.job.enabled=false

#Diff Report
statistic-app.analytics.diff-report.diff-report-out-folder-path=${DIFF_REPORT_OUT_FOLDER_PATH:}
